# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/chat_server.rb'

Hoe.new('ChatServer', ChatServer::VERSION) do |p|
  # p.rubyforge_name = 'ChatServerx' # if different than lowercase project name
  p.developer('Peter Held', 'peter.t.held@gmail.com')
end

# vim: syntax=Ruby
